### ISSUE TITLE
[BUG] - Update does not restart to new update version.

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/NASR2SCT#10]
**Describe the bug**
When there is an update for a new version, after the program downloads and "updates", a second program opens and asks if you want to update even though it was just updated.

**Expected behavior**
The restart should start the new version.

**Screenshots**
![image](https://user-images.githubusercontent.com/38259407/101262692-c71b1a00-36fd-11eb-8142-9f3f9e262a37.png)
![image](https://user-images.githubusercontent.com/38259407/101262702-d8642680-36fd-11eb-87f2-7bfeafb7ccf9.png)

**Comment by Nikolai558** [comment]
I have implemented a temporary fix for this issue. In version 0.5.4, the program will alert the user and exit. The user has to manually start the program again in order for it to run the updated version.

**Comment by KSanders7070** [comment]
Fixed with V-0.6.3
