### ISSUE TITLE
TODO: WIN OS V# Compatibility

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#101]
Add in manual the lowest version of Windows required to run.

**Comment by Nikolai558** [comment]
Looks Like Windows 8.1 is the lowest Windows version NASR2SCT will run on. I am working on verifying this right now.

**Comment by Nikolai558** [comment]
If user is running Windows 8.1 and does not have .net framework 4.7.2 installed, when they run setup.exe it will prompt the user to install .net framework. Once they click yes, it will take them to Microsoft's .net framework site. Once they select the correct framework (.net framework 4.7.2) and install it NASR2SCT will work. 
NOTE: This is not the program asking to install the .net framework, this is the Windows OS doing this function trying to remidy the fact that .net is not installed. 

![image](https://user-images.githubusercontent.com/38259407/120709902-b06e3980-c47a-11eb-8170-94d44958dbf4.png)
![image](https://user-images.githubusercontent.com/38259407/120710354-4a35e680-c47b-11eb-8f01-d2bdbae66002.png)
![image](https://user-images.githubusercontent.com/38259407/120710437-5e79e380-c47b-11eb-8ee4-d36306b43f02.png)

**Comment by Nikolai558** [comment]
Added.
