### ISSUE TITLE
[BUG] -Wx Stations without DATA

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#104]
I have found numerous weather stations output by NASR2SCT that don't have the ability to pull weather from VATSIM. I don't remember the IDs but there are a few on the boarder of ZLC Sector 17 and ZDV.

I have an idea that we could use this page... and it has the station NAME on it as well.

https://www.cnrfc.noaa.gov/metar.php

**Comment by KSanders7070** [comment]
K97M and KM46 are two station examples that show up on the Wx filter but is not actually a station we can get metar data from on VATSIM.

K97M even shows up in the link that I sent but if you select it, it returns a "Station does not exist". Maybe we can check for that and just not print it, if it does that.

**Comment by Nikolai558** [comment]
Added / Fixed in version 0.8.1

Pulls WX stations from Vatsim Metar Website. We might want to try this for a while and see if it is working properly....

**Comment by Nikolai558** [comment]
Keep Issue open for a while.

**Comment by KSanders7070** [comment]
**Foundational Data:**

- Find all of the METAR stations from https://metar.vatsim.net/metar.php?id=all that also match with the NOAA_METAR_STATION list and print them to a METAR_MASTER list.

- Create a STATION_HISTORY list that matches the METAR_MASTER list but comma separated with the current date/time as the second item.



**Normal Run:**

_Ideally, the following script would run once an hour, on the half hour (30min) mark:_

- Make a duplicate METAR_MASTER list to be used in case of an unexpected crash or corrupt resource file.

- Print all station IDs from the NOAA METAR station site to the NOAA_METAR_STATION list.

- Print all the station IDs from https://metar.vatsim.net/metar.php?id=all that match with an ID from the NOAA_METAR_STATION list to a NOAA_VATSIM_TEMP list.

- Every station ID that was printed to the NOAA_VATSIM_TEMP list, should be cross referenced with the STATION_HISTORY list. If the station ID is found in the STATION_HISTORY list, then the date/time will be replaced with the current data/time. If the station ID was not found in the STATION_HISTORY list, then the station ID should be added to the STATION_HISTORY list with the current date/time.

- Clear the METAR_MASTER list.

- Read the STATION_HISTORY list. For every station that has a date/time reading less than 28 days, print that station ID to the METAR_MASTER list.

- Print the METAR_MASTER list to a resource file on the GitHub repo.


_Note: NASR2SCT should pull from the METAR_MASTER list for a source of station IDs to look for._

**Comment by KSanders7070** [comment]
UDPATE:
We are going to utilize this source for the wx stations from now on: https://w1.weather.gov/xml/current_obs/index.xml

**Comment by Nikolai558** [comment]
Fixed / Added 0.8.3
