### ISSUE TITLE
[BUG] - File DL Checker

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#105]
After every file is downloaded, there should be a check to make sure it downloaded fully/correctly.

If failed, display a message that that file failed and we are trying again.

Maybe have a timeout to check the users internet connection in general by pinging Google or something.

Display messages accordingly.

**Comment by Nikolai558** [comment]
Added / Fixed in v0.8.1 

Program will display message then once user clicks "ok" program will close.
