### ISSUE TITLE
[BUG] -WX Station without WX Return

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#11]
**Describe the bug**
10U (K10U) shows as a weathers station on the scope but does not actually have a report to give.

**Expected behavior**
These type of stations should not be in the export. I noticed that it is a "SA" wx type. We grab the info if it is only SA because of the station "NFL" which is a "SA UA".. the UA shouldn't be the determining factor. There is something we are missing.

**Comment by Nikolai558** [comment]
Fixed in Version 0.5.4
