### ISSUE TITLE
[FEAT REQ.] - FAQ Button

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#111]
Create a FAQ button on the tool bar.

Link to this:

https://docs.google.com/presentation/d/e/2PACX-1vSlhz1DhDwZ-43BY4Q2vg-ff0QBGssxpmv4-nhZlz9LpGJvWjqLsHVaQwwsV1AGMWFFF_x_j_b3wTBO/embed?

**Comment by Nikolai558** [comment]
Added Version 0.8.1
