### ISSUE TITLE
[FEAT REQ.] - APT & NAV XML output

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#12]
**Is your feature request related to a problem? Please describe.**
To help with NAVDATA updates that also would have a vERAM GEOMAP, It would be nice to have the program output data like the attached files.
[Airport Format.txt](https://github.com/Nikolai558/NASR2SCT/files/5662788/Airport.Format.txt)
[VOR Symbol Format.txt](https://github.com/Nikolai558/NASR2SCT/files/5662789/VOR.Symbol.Format.txt)

**Comment by KSanders7070** [comment]
APT BCG and Filter, let's make it 10 for both of them for now.

**Comment by Nikolai558** [comment]
Added in Version 0.5.4
