### ISSUE TITLE
[BUG] - Text blurry on HiDPI screens

### ISSUE THREAD

**Issue by wiggleforlife** [Nikolai558/NASR2SCT#128]
**Describe the bug**
Text is blurry on HiDPI screens with more than 100% scaling. Applies to WinForms and Windows dialogues.

**Expected behavior**
Text should be clear as it is on 100% scaling.

**Screenshots**
Taken on a 12.3" 267 DPI monitor at 150% scaling. Please note that the sizing of the window is a bug on my branch., not a release. The same blurriness applies to a proper release.
![SharedScreenshot](https://user-images.githubusercontent.com/46230102/139494847-b1feb880-e350-407b-818f-27f0c7fc7e45.jpg)

**Comment by KSanders7070** [comment]
SOLUTION? - https://youtu.be/oIxpqXHdZAQ

**Comment by KSanders7070** [comment]
added a manifest. Will see if this works later.

**Comment by Nikolai558** [comment]
This has hopefully been fixed in 0.8.3. Let me know otherwise

**Comment by KSanders7070** [comment]
With 0.8.3, it now looks like this:
![unknown](https://user-images.githubusercontent.com/63331106/140000769-50e6219b-0349-4b07-a27c-d6766b8dd388.png)

**Comment by Nikolai558** [comment]
Refer to new bug. This is a seperate issue. #135
