### ISSUE TITLE
[BUG] - Frequent Telephony Site Crash

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#129]
**Describe the bug**
When DOWNLOADING FILES, many times the FAA Telephony site times out and causes NASR2SCT to crash.

**Suggested Solution**
Utilize cURL/BATCH to get the HTML download instead of WebClient function.

**Comment by Nikolai558** [comment]
Fixed / Added 0.8.3

Uses curl now. Should fix this. If this is a problem still please reopen this issue.
