### ISSUE TITLE
[FEAT REQ.] - Wx Station GeoMap

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#15]
**Is your feature request related to a problem? Please describe.**
Need a GeoMap format for Wx Stations output.

**Describe the solution you'd like**
Same as: https://github.com/Nikolai558/NASR2SCT/issues/12
Format example attached
[wx station format.txt](https://github.com/Nikolai558/NASR2SCT/files/5668400/wx.station.format.txt)

**Comment by Nikolai558** [comment]
Added in Version 0.5.5

**Comment by KSanders7070** [comment]
Is it possible to get the output file to be named:
WX_STATIONS_GEOMAP.xml

**Comment by Nikolai558** [comment]
Output name is now WX_STATIONS_GEOMAP.xml in version 0.5.5
