### ISSUE TITLE
[FEAT REQ.] - AWY GeoMap

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#16]
**Is your feature request related to a problem? Please describe.**
Need an AWY GeoMap output.

**Describe the solution you'd like**
Same as https://github.com/Nikolai558/NASR2SCT/issues/15
This needs to include ALL airways (low, high, ats)
Format attached.
[Airways format.txt](https://github.com/Nikolai558/NASR2SCT/files/5668428/Airways.format.txt)

**Comment by KSanders7070** [comment]
Can I get the output file to be named:
AWY_GEOMAP.xml

**Comment by Nikolai558** [comment]
Added in Version 0.5.6

**Comment by KSanders7070** [comment]
Added in V-0.5.6
