### ISSUE TITLE
[FEAT.REQ] Create "TEST_SECTOR.sct2"

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#2]
When done with everything, can you make a "Combine all" to a test sector.sct2?

BATCH file included with this request submission.

@ECHO OFF

CD "%PROJ_DIR%"

break>TEST_SECTOR.sct2

(
ECHO [INFO]
ECHO TEST_SECTOR
ECHO TST_CTR
ECHO XXXX
ECHO N043.31.08.418
ECHO W112.03.50.103
ECHO 60.043
ECHO 43.536
ECHO -11.8
ECHO 1.000
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "APT.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "AWY.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "FIX.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "NDB.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "VOR.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

(
type "WxStations.sct2"
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
ECHO.
)>>TEST_SECTOR.sct2

PAUSE

**Comment by Nikolai558** [comment]
Feature added, Will be in next release.
