### ISSUE TITLE
[FEAT REQ.] - .(AWY)F Alias

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#20]
For the purposes of this post, "FIX" will be defined as any NAVAID, Intersection, Waypoint, Airport, or any defining point along an airway.

**Describe the solution you'd like**
The PARSER outputs AWY_Alias.txt that draws the fixes for that airway on the vERAM scope using the Root .FF command.

FORMAT:
.(AWY_ID)F .FF (FIX) (FIX) (FIX) ect...

EXAMPLE:
.V200F .FF ENI LAPED DALON ILA YUBBA RAILE MRGGO RANGO SIGNA TRUCK VERDI FMG

So basically print the first point of every new line. Then print the second waypoint of a new line if it is the last line to be drawn.

This will get tricky for airways that have gaps. To use the previous .V200 as an example, that airway has a gap after FMG and picks back up at BVL. So it should actually look like this:
.V200 .FF ENI LAPED DALON ILA YUBBA RAILE MRGGO RANGO SIGNA TRUCK VERDI FMG BVL ZONSU BAGGI CEVAR STACO ANEYI FFU PANEL NONTY MTU FECYE OHAPE BONGO RACER EKR JESIE RLG

Then to complicate things further, there are times when there is a "GAP" indicated for the airway, the airway data is separated in the NASR files even though they share the same AWY ID.

Example: V311
There are two groups of V311 in the FAA NASR data separated by 7,600 lines of data yet the end of the first group didn't indicate a GAP. When the user types .V311, they should still be getting every fix for both of the groups .

or....

You can interrogate the AWYModel for all AWY_IDs and get the associated fixes and then combine them all.

**Comment by Nikolai558** [comment]
Added in version 0.5.5

**Comment by KSanders7070** [comment]
Can I get the output file to be named:
AWY_ALIAS.txt

**Comment by Nikolai558** [comment]
Output file is now named AWY_ALIAS.txt in version 0.5.5
