### ISSUE TITLE
[FEAT REQ.] - Directory Restructure

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#24]
**Describe the solution you'd like**

1) Considering the ISR folder will not hold ONLY ISRs, I suggest renaming that folder to ALIAS.

2) Test sectorFile.sct2 put into the VRC folder.

**Comment by Nikolai558** [comment]
Is this the same thing as #22 ? 

If so Fixed/added in Version 0.5.5

SectorFile.sct2 will now be in the VRC folder in Version 0.5.5.
