### ISSUE TITLE
[FEAT REQ.] - Draw All DP/STARs

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#28]
**Describe the solution you'd like**
An output of all DPs and STARs Line-Draw Diagrams from the FAA NASR STARDP.txt file.
Along with a .LEEHYF alias to draw all waypoints along the route.

**Additional context**
Attached you will find a batch file that draws all DPs and STARS. There are some errors with FAA data that have been reported that will draw a line all the way accross the country... they will grab "GRREN" data when they meant "GRENN" as a waypoint. There is nothing you can do about this except report it when you see it.
[STARDP_PARSER.txt](https://github.com/Nikolai558/NASR2SCT/files/5715937/STARDP_PARSER.txt)

**Comment by Nikolai558** [comment]
Added Version 0.5.6

**Comment by KSanders7070** [comment]
Added in V-0.5.6
