### ISSUE TITLE
[FEAT REQ.] - FAA Chart Recall Commands

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#29]
**Describe the solution you'd like**
Alias output in the format of the vZLC ARTCC Airport Diagram and DP/STAR FAA Chart Recall commands.

**Additional context**
I think utilizing the same logic form your ARTCC-Publication-Parser this could fairly easily be done.
This would allow FEs to only have to manually edit Instrument Approach Procedures (which I don't think there is an easy way to automated the alias syntax for).

**Comment by Nikolai558** [comment]
Added Version 0.5.6

**Comment by Nikolai558** [comment]
Added in Version 0.6.9
