### ISSUE TITLE
[FEAT REQ.] - ICON

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#34]
![NASR_2_SCT_icon_PNG](https://user-images.githubusercontent.com/63331106/102722933-98429d80-42d2-11eb-8a69-9a8bfa78b7b5.png)
[NASR_2_SCT_icon.zip](https://github.com/Nikolai558/NASR2SCT/files/5721410/NASR_2_SCT_icon.zip)

**Comment by KSanders7070** [comment]
Consider adding the actual PNG to the resource files as well in case we wish to use this in a larger format later on.

**Comment by Nikolai558** [comment]
Added in Version 0.6.4
