### ISSUE TITLE
[FEAT REQ.] SCT RUNWAY DATA

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#4]
**Is your feature request related to a problem? Please describe.**
-No

**Describe the solution you'd like**
Provide the SECTOR File [RUNWAY] data.

**Describe alternatives you've considered**
-Not having the [RUNWAY] Data (which I am fine with).

**Additional context**
-Low priority, maybe never do it, as the data isn't really useful and actually contributes to fairly unrealistic controlling techniques.
-Your program already pulls the data required for this section.
(Runway Group (runway1) (runway2)) (Rwy1 MagHdg) (Rwy2 MagHdg) (Rwy1 (LAT) (LON)) (Rwy2 (LAT) (LON)) ;(comment-I would suggest APT ID)
![RWY DATA for NASR2SCT](https://user-images.githubusercontent.com/63331106/101110325-bc01a600-35a6-11eb-8fbc-7cd59b809267.jpg)

**Comment by Nikolai558** [comment]
Added in Release 0.5.2
