### ISSUE TITLE
[BUG] - Missing Fonts

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#41]
**Describe the bug**
Doesn't account for menu fonts not being installed on the users machine.

**Expected behavior**

https://brutaldev.com/post/installing-and-removing-fonts-using-c
![image](https://user-images.githubusercontent.com/63331106/102744913-ebdfd600-4328-11eb-842b-7f476fab3d78.jpeg)

**Comment by Nikolai558** [comment]
Fixed Version 0.6.5
