### ISSUE TITLE
[BUG] - Start New Version After Update

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/NASR2SCT#42]
**Describe the bug**
Some people have issues after the update process is done. They get an error stating the program can not be found. This is caused by the batch file trying to call it before the computer registers that it is indeed there. 

**Possible Fix**
- Increase the "ping -n amount" in the batch file used to start the new program.
- Create a loop in the batch file so that it tries again if it fails.  

**To Reproduce**
1. When an update is released, click yes to the update
2. Wait for Program to process update 
3. Error Message will SOMETIMES be displayed.

**Expected behavior**
Program should start especially since it is indeed located there.

**Screenshots**
![image](https://user-images.githubusercontent.com/38259407/102795622-49e0dd80-436a-11eb-894e-effd773362d2.png)
![image](https://user-images.githubusercontent.com/38259407/102796107-fde26880-436a-11eb-8d73-cffcab922eab.png)

**Comment by KSanders7070** [comment]
Considering batch file for loop "if exist" and let it repeat a few times but put it on a count so that it can escape after a bit.

**Comment by KSanders7070** [comment]
This batch script will check if the file exists, wait ~2seconds and check again. It will do this 6 times. If it finds it, it tries to start the .exe. If at the end of the 6 loops it still doesn't find it, it still tries to start the .exe and will result in the same error.

You may remove the spaces between lines in the batch.
Line 11 (ECHO %COUNT%) can be deleted.

[NASR2SCT_IF_EXIST.txt](https://github.com/Nikolai558/NASR2SCT/files/5725810/NASR2SCT_IF_EXIST.txt)
![Screenshot_3](https://user-images.githubusercontent.com/63331106/102808574-7f97bd80-438e-11eb-8fd2-6397de687760.jpg)

**Comment by Nikolai558** [comment]
Fixed Version 0.6.7
