### ISSUE TITLE
[BUG] - Facility ID User input Check

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/NASR2SCT#43]
**Describe the bug**
I know common sense says don't put anything besides letters/numbers in this box, HOWEVER, this would be really easy to check and make sure only letters/numbers are in the box. If the user does put any special symbols, it could have some unwanted consequences in VRC.

**To Reproduce**
1. Insert any symbol or character that is not a letter or number
2. Run
3. Open VRC and load one of the ISR
4. Use that alias command

**Expected behavior**
Don't allow user to continue if it contains anything other than ascii letters or numbers. Also, might be worth considering a "Max-length" I know if a user puts more than (I think) 255 characters in the box, the program will have a fit and possibly crash. Not to mention VRC will most likely not appreciate 255 characters.  Again, this goes with common sense but if I am encouraging people to break the program this would be one of the things I would try to break it.

**Comment by KSanders7070** [comment]
Consider removing the FAC ID choice completely and default the FAC ID to FAA.

**Comment by KSanders7070** [comment]
This could be reenabled later on when we do something significant with the facility

**Comment by Nikolai558** [comment]
Chose to disable the field entirely until more functionality is available. Fixed/added Version 0.6.9
