### ISSUE TITLE
[BUG] - Chart Recall (RNP) with L/R/C Designator

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#55]
**Describe the bug**
Incorrect command given for an airport that has (RNP) in it and a runway L/R/C designator. Ones without a L/R/C designator or has (GPS) instead works just fine.

This one is fine: DENVER INTL-RNAV (RNP) Z RWY 07
This one is not:  DENVER INTL-RNAV (RNP) Z RWY 16L

![Screenshot_1](https://user-images.githubusercontent.com/63331106/103131489-f96dc680-466e-11eb-8466-65f4d1ff5221.jpg)

**Comment by Nikolai558** [comment]
Fixed Version 7.0.1
