### ISSUE TITLE
[BUG] - Mutli-APT DP/STARs Commands

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#57]
**Describe the bug**
When completing a DP/STAR command (chart recall/fixes/etc...) for a procedure that serve multiple airports, it only provides the data for one of the charts.

**To Reproduce**
1. .KAYLNC
2. .KAYLNF

1-Brings up the VLL airports version of this procedure when DTWs version may be wanted.
2-Seems to draw the fixes for DTWs version or maybe it draws all versions together.

**Expected behavior**
We may have to put the airport code at the beginning of the syntax:
1. .VLLKAYLNC .DTWKAYLNC
2. .VLLKAYLNF .DTWKAYLNF

**Comment by Nikolai558** [comment]
Fixed Version 0.7.1
