### ISSUE TITLE
[FEAT REQ.] - APT TEXT GEOMAP

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#58]
**Describe the solution you'd like**
An .xml output "AIRPORT_TEXT_GEOMAP.xml" formatted like the attached file.
The text format:
(APT ICAO code, ELSE: FAA ID) (APT Name)

[AIRPORT_TEXT_GEOMAP.txt](https://github.com/Nikolai558/NASR2SCT/files/5758484/AIRPORT_TEXT_GEOMAP.txt)

**Comment by Nikolai558** [comment]
Added Version 0.7.1
