### ISSUE TITLE
[FEAT REQ.] - NAV TEXT GEOMAP

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#59]
**Describe the solution you'd like**
An .xml output "NAVAID_TEXT_GEOMAP.xml" formatted like the attached file.
The text format:
(NAVAID ID) (NAVAID Name) (NAVAID Type)

[NAVAID_TEXT_GEOMAP.txt](https://github.com/Nikolai558/NASR2SCT/files/5758487/NAVAID_TEXT_GEOMAP.txt)

**Comment by Nikolai558** [comment]
Added Version 0.7.1
