### ISSUE TITLE
[BUG] - AIRPORTS_GEOMAP missing airports

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#64]
**Describe the bug**
When drawing the new AIRPORT_TEXT_GEOMAP, there are text points for airports that don't have a symbol.
Take for example: 79FD, FA53, FL42 that don't have airport symbols in the AIRPORTS_GEOMAP.xml but KPCM, KLAL, and KBOW do.

At first, it appears that only fields with an ICAO get a symbol but 0L9 gets a symbol and has no ICAO code.

![APT TEXT](https://user-images.githubusercontent.com/63331106/103471407-eda89100-4d4d-11eb-9c36-9b34fb25365c.jpg)

**Comment by Nikolai558** [comment]
Fixed Version 0.7.2
