### ISSUE TITLE
[BUG] - PAE Chart Recalls Formatting

### ISSUE THREAD

**Issue by MacMinnS** [Nikolai558/NASR2SCT#67]
The formatting for the Paine ILS Y/Z 16R is incorrect:

.PAEIYC .OPENURL https://aeronav.faa.gov/d-tpp/2014/00142IYLY16R.PDF  ; SNOHOMISH COUNTY (PAINE FIELD)-ILS Y OR LOC Y RWY 16R
.PAELYC .OPENURL https://aeronav.faa.gov/d-tpp/2014/00142IYLY16R.PDF  ; SNOHOMISH COUNTY (PAINE FIELD)-ILS Y OR LOC Y RWY 16R
.PAEIZC .OPENURL https://aeronav.faa.gov/d-tpp/2014/00142IZLZ16R.PDF  ; SNOHOMISH COUNTY (PAINE FIELD)-ILS Z OR LOC Z RWY 16R
.PAELZC .OPENURL https://aeronav.faa.gov/d-tpp/2014/00142IZLZ16R.PDF  ; SNOHOMISH COUNTY (PAINE FIELD)-ILS Z OR LOC Z RWY 16R

There appears to be others as well.
![image](https://user-images.githubusercontent.com/77217017/104112282-b8a2be00-52ba-11eb-9ea8-e6e3c843b47c.png)

**Comment by Nikolai558** [comment]
Fixed in Version 0.7.3

Thanks for catching this Skylar! Let me know if you find any more!
