### ISSUE TITLE
[FEAT REQ.] - Display Output Directory

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#69]
**Describe the solution you'd like**
Display the user chosen output directory during the "processing" stages.

**Comment by Nikolai558** [comment]
Added in version 0.7.5

![image](https://user-images.githubusercontent.com/38259407/104827929-dcb55080-5820-11eb-96d5-1c37c88c0c57.png)

**Comment by Nikolai558** [comment]
Added Version 0.7.5
