### ISSUE TITLE
[BUG] - IAP Naming Conventions

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#71]
The following is the standard for creation of Instrument Flight Procedures. Take a look at "Section 1-6. Identification of IFPs".
I have attached a highlight from that section.

Take for example: "VOR OR TACAN-A". That would be:
VOR-A & TACAN-A
![COMBINE CHART STANDARD](https://user-images.githubusercontent.com/63331106/104461803-c9cf2180-557d-11eb-8501-97e6707a25bc.jpg)

**Comment by Nikolai558** [comment]
Fixed in Version 0.7.4
- IAP Variant Naming Conventions Bug #71
	- If there are multiple IAP's in one chart (i.e. "ILS Y **OR** LOC/DME RWY 06" ; "VOR **OR** GPS-B") and one of them has a variant but the other does not, the scratch pad code will be as if both of them had the same variant.
