### ISSUE TITLE
[FEAT REQ.] - UNINSTALL Button

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#73]
I would like to see a button up on the menu bar "UNINSTALL"

When selected, it opens a dialog box explaining the directories that will be removed if the user selects "Yes".

If the user selects yes, it will write a batch file to start this batch file: https://github.com/Nikolai558/NASR2SCT/blob/development/UNINSTAL_NASR2SCT.bat

**Comment by Nikolai558** [comment]
added V-0.7.6
