### ISSUE TITLE
[BUG] - Cycle 2101 Chart Recalls Write 2014 in links

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#75]
**Describe the bug**
.ADKTMC .OPENURL https://aeronav.faa.gov/d-tpp/2014/AKTO.PDF#nameddest=(ADK)  ; ADAK-TAKEOFF MINIMUMS

**Expected behavior**

This should be 2101.

**Comment by Nikolai558** [comment]
Fixed Version 0.7.5
