### ISSUE TITLE
[BUG] -TestSctFile Doesn't Have [FIXES]

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#8]
**Describe the bug**
Title says it all.

**Comment by Nikolai558** [comment]
![image](https://user-images.githubusercontent.com/38259407/101259550-9c719700-36e6-11eb-8e1f-1ee5ff4851be.png)
Accidental comment out of the portion that calls fixes. 

Fixed in Version 0.5.3
