### ISSUE TITLE
[BUG] - UNISTALL Access Denied

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#80]
**Describe the bug**
Appears to deny access to the APPDATA\LOCAL\NASR2SCT folder

![UNSTL ISSUE](https://user-images.githubusercontent.com/63331106/106698667-410d3980-65af-11eb-8df0-007fd59eb3de.jpg)

**Comment by KSanders7070** [comment]
I believe doing our "batch writing a batch" will fix this.

**Comment by Nikolai558** [comment]
Completed Version 0.7.7
