### ISSUE TITLE
[FEAT REQ.] - Add ARTCC Publication Parser

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#83]
Would like to see the ARTCC Publication Parser program be added to this program.
This would also make use of the Facility box.

**Comment by Nikolai558** [comment]
Great idea! Would it be a separate button, or would it just do it if next ARIAC is selected and the meta data is available?

**Comment by KSanders7070** [comment]
Not sure. Benefits to both. Seeing how it is tied to the d-TPP meta file, it would need the same warning that the chart recall commands are given when selecting the "next AIRAC" when the new data isn't available yet.

**Comment by Nikolai558** [comment]
Added in Version 0.7.7
