### ISSUE TITLE
[FEAT REQ.] - Don't use "Deleted_Job" links

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#84]
Suggest not creating a command for publication links that have "DELETED_JOB" in the PDF name.

![image](https://user-images.githubusercontent.com/63331106/111042114-b3bcd080-8409-11eb-9aab-9882d3cd2b4b.png)

**Comment by Nikolai558** [comment]
Completed Version 0.7.7 

Will not consider PDF NAMES "DELETED" as valid Alias Commands.
