### ISSUE TITLE
[BUG] - "Run Again" process is broken

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/NASR2SCT#86]
**Describe the bug**
Something weird happens when you run NASR2SCT two times without closing it. Once "Run Again" button is clicked, and a different AIRAC is selected, and Start is pushed, the program downloads the files it needs. Then it says "Complete" but the program hasn't even unzipped the download folders. 

**To Reproduce**
1. Run the first AIRAC
2. Once complete, Click "Run Again"
3. Choose the other AIRAC
4. Click Start

**Expected behavior**
Should be able to run it as many times as you want or need without having to close the program first.

**Comment by KSanders7070** [comment]
When considering the priority level or allocation of time for development, I believe it would be better to just remove the "run again" option.

**Comment by Nikolai558** [comment]
Run Again Removed in Version 0.7.7

Need to remove artifact code, but I will wait for a bit to do that.
