### ISSUE TITLE
[FEAT REQ.] - JSON Output

### ISSUE THREAD

**Issue by Raajheer1** [Nikolai558/NASR2SCT#88]
In an attempt to more accurately calculate route length for the AADCs, I am manually calculating the distance between each point on the route. To do so I need data for each intersection and information about the airways.

Create a secondary output that writes to a JSON file rather than the .XML file. 

Suggested format:
```yaml
{ "FLATI": [{ "lat": "48.14530182", "long": "-116.2139969" }],  "LAWGR": [{ "lat": "49.14530182", "long": "-115.2139969" }], "J56": ["TCH", "CHE", "GOULL", "FROGS"], ... }
```

I looked at https://flightplandatabase.com/dev/api and it worked great. Their route distance calculator was very accurate my only issue was that it was rate-limited pretty hard to 1,500 calls/month which isn't nearly enough.

If it isn't too much work possibly add iata with lat/long as well to that JSON file.

**Comment by KSanders7070** [comment]
This request is outside the scope of what this program is intended for so this would be better off as a standalone parser.

However, it seems like you could easily create a simple parser in Python or something to utilizes the NASR2SCT output files "Waypoints.xml" and "AWY_ALIAS.txt" to create the JSON you are wanting.

I will leave this open for more discussion and to see Nik's thoughts.

**Comment by KSanders7070** [comment]
I just spoke to Raaj via voice. He now understands how to use our output files to create his JSON. Closing this request.
