### ISSUE TITLE
[BUG] - ARTCC HIGH  030520 030530 Line

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#9]
**Describe the bug**
A ZNY line that was not returned to beginning.

**To Reproduce**
1. Run parser with 03DEC2020 effective date.

**Expected behavior**
Line 896 on the ARTCCC HIGH output (Sequence: 030520 030530) should be (030520 030250).

I am not sure you are resetting the "firstPoint" after getting a "return to beginning" line.
In this case, the firstPoint of the next segment is sequence number 030530 but that is still ZNY HIGH, which is what I think is tripping up your logic.

Just for clarification, it should be the following:
LINE   SEQ1   SEQ2

895   030510   030520
896   030520   030250
897   030530   030540

**Comment by Nikolai558** [comment]
Will be fixed in V-0.5.3.
