### ISSUE TITLE
[BUG] - 0.7.8 Direct Install Broke

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/NASR2SCT#96]
When installing 0.7.8 directly from GH, it opens to this error:
![image](https://user-images.githubusercontent.com/63331106/117075516-f3fe4800-ad02-11eb-9d69-7a52735ab58a.png)

If you install 0.7.7 and update to 0.7.8, everything is fine.

**Comment by Nikolai558** [comment]
Something went wrong when I packaged Release 0.7.8

This has been fixed and Fresh install works on 0.7.9
