### ISSUE TITLE
[BUG] - Program will not setup - WINDOWS 7

### ISSUE THREAD

**Issue by zabfe** [Nikolai558/NASR2SCT#99]
Clicked setup and got the dialogue "Has stopped working; close Program" See attached picture. I have a WIN 7 machine if that makes a difference.
![NASR2SCTStop](https://user-images.githubusercontent.com/84881946/119744505-0589ca00-be41-11eb-8d4b-9b9b96a6981f.jpg)

**To Reproduce**
1. Did this several times and with several older versions; same result
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Comment by Nikolai558** [comment]
@zabfe,

Can you check a couple of things for me. In your file explorer, go to `C:\Users\{your username}\AppData\Local`. Do you have a folder in there called "NASR2SCT"? If you do what all is in that folder? 
![image](https://user-images.githubusercontent.com/38259407/119745699-e3497980-be4b-11eb-8858-192c2654c46d.png)

Also, can you check in one more directory for me. Go to `"C:\Users\{your username}\AppData\Local\Temp"`. Do you have a folder in there called "NASR2SCT"? If you do please tell me everything that is in that directory. 
![image](https://user-images.githubusercontent.com/38259407/119745733-f3615900-be4b-11eb-9c8f-1829d2f307cd.png)


I can't guarantee support for Windows 7, but I am willing to look into it and see if this is an easy fix.

**Comment by zabfe** [comment]
Everything is in the first folder; see the picture
The NASR2SCT folder in the Local/Temp is empty
![NASR2SCTStop1](https://user-images.githubusercontent.com/84881946/119746287-fc9af780-be44-11eb-8965-f448dc063c8b.jpg)

**Comment by Nikolai558** [comment]
@zabfe,

I am sorry to say this but I can not figure out how to make this program compatible with Windows 7. I have researched and tried a couple of different things but all have failed. If you know someone that could help get this compatible with Windows 7, I would be open for ideas. However, without further help from someone else, I can not make this compatible.

**Comment by zabfe** [comment]
Thanks for trying; at least I know it is because I am a WIN 7 hold out. When I upgrade to something higher I am sure it will work. You can close this issue if you want
